### ISSUE TITLE
gmpy not found on a fresh install

### ISSUE THREAD

**Issue by giorgiop** [n1analytics/python-paillier#35]
```
src/gmpy.h:106:19: fatal error: gmp.h: No such file or directory
#  include "gmp.h"
```
I solved installing it with `apt-get install  libgmp3-dev`

**Comment by giorgiop** [comment]
Also `mprf` missing on my system.

**Comment by giorgiop** [comment]
`mpc` not found either. Installed with `sudo apt-get install libmpc-dev`

**Comment by giorgiop** [comment]
For the record, I am on a old Ubuntu 14.04

**Comment by razi-rais** [comment]
I ran into this issue and end creating a Docker image to avoid going through the issue again. 

Here is the full set of commands.

apt-get update \
&& apt-get install python3 -y \
&& apt-get install python3-pip -y \
&& apt-get install libgmp3-dev -y \
&& apt-get install -y libmpfr-dev libmpfr-doc libmpfr4 libmpfr4-dbg \
&& apt-get install libmpc-dev -y \
&& pip3 install phe

**Comment by iedmrc** [comment]
> I ran into this issue and end creating a Docker image to avoid going through the issue again.
> 
> Here is the full set of commands.
> 
> apt-get update
> && apt-get install python3 -y
> && apt-get install python3-pip -y
> && apt-get install libgmp3-dev -y
> && apt-get install -y libmpfr-dev libmpfr-doc libmpfr4 libmpfr4-dbg
> && apt-get install libmpc-dev -y
> && pip3 install phe

To copy paste:

```
apt-get update \
&& apt-get install python3 -y \
&& apt-get install python3-pip -y \
&& apt-get install libgmp3-dev -y \
&& apt-get install -y libmpfr-dev libmpfr-doc libmpfr4 libmpfr4-dbg \
&& apt-get install libmpc-dev -y \
&& pip3 install phe
```
