### ISSUE TITLE
Decrypt() is giving encrypted_number was encrypted against a different key

### ISSUE THREAD

**Issue by razi-rais** [n1analytics/python-paillier#54]
While decrypting the encrypted number using the decrypt method I am getting an error:

`[privatekey.decrypt(x) for x in deserialized_numbers]
`
`ValueError: encrypted_number was encrypted against a different key!`

However, if I use the same private key and use the raw_decrypt method instead it work as expected and decrypt the cipher text into raw plain text. I actually do need simple plain text and not sure how to covert from raw plain text back to simple plain text so it blocked me from moving further.  

`Works`
`[privatekey.raw_decrypt(x.ciphertext()) for x in deserialized_numbers]`
 
Also deserialized_numbers are used as explained in the [documentation](https://python-paillier.readthedocs.io/en/stable/serialisation.html#basic-json-serialisation) 

Wondering what I did missed.

**Comment by hardbyte** [comment]
Can you show how you are encrypting as well? I suspect that your encrypted numbers (`deserialized_numbers`) are not being deserialized using the correct public key.

If you really only need to encrypt/decrypt raw unsigned integers (without any encoding) you can use `pk.raw_encrypt` and `sk.raw_decrypt`:

```
import json
import phe.paillier as paillier


def raw_enc_dec():
    x = 301
    pk, sk = paillier.generate_paillier_keypair()
    enc = pk.raw_encrypt(x)
    print(sk.raw_decrypt(enc))


def raw_enc_dec_serial():
    x = 301
    pk, sk = paillier.generate_paillier_keypair()
    enc = pk.raw_encrypt(x)

    enc_with_one_pub_key = {}
    enc_with_one_pub_key['public_key'] = {'n': pk.n}

    enc_with_one_pub_key['values'] = [
        (str(enc), 0)
    ]

    serialised = json.dumps(enc_with_one_pub_key)


    received_dict = json.loads(serialised)
    received_pk_info = received_dict['public_key']
    public_key_rec = paillier.PaillierPublicKey(n=int(received_pk_info['n']))

    rx = received_dict['values'][0]
    print(sk.decrypt(paillier.EncryptedNumber(public_key_rec, int(rx[0]), int(rx[1]))))


if __name__ == '__main__':
    raw_enc_dec()
    raw_enc_dec_serial()
```

**Comment by razi-rais** [comment]
Thanks @hardbyte , it was an issue with the public key. Closing the issue now.
