### ISSUE TITLE
How to save encrypted data to a file

### ISSUE THREAD

**Issue by Luidy** [n1analytics/python-paillier#72]
Hello.
I wanna store the encrypted data in a file.
Like this data.

encrypted_a = public_key.encrypt(encoded_a)

I need to save the 'ciphertext' to save the data, but I do not know how to save the method (ciphertext) to a file.
How can I store the 'ciphertext'?

I'll wait for your answer.
Thank you.

**Comment by hardbyte** [comment]
Hi Luidy, this is the same question as how to safely serialize the data before sending over the network. I suggest looking at https://python-paillier.readthedocs.io/en/latest/serialisation.html

**Comment by Luidy** [comment]
Thanks for your answer.
Is it the most appropriate way to store the 'encoding data' and 'encrypt()' it?

**Comment by hardbyte** [comment]
As long as you are storing the public key and each encrypted numbers ciphertext & exponent you'll be fine. Just make sure you can recreate the encrypted number via the initializer:
```python
paillier.EncryptedNumber(public_key, ciphertext, exponent)
```
