### ISSUE TITLE
r should be an relatively prime of n

### ISSUE THREAD

**Issue by weiwee** [n1analytics/python-paillier#77]
reproduce code:
```python
import phe
phe.__version__ # 1.4.0
pub, pri = phe.generate_paillier_keypair()
pri.p, pri.q
# (137880798437578214900337271069318106154424919142726058921733331447119516175916806163325332165924413687695975370017367042502971968100049246600973362433927577010508232499209110302933911212111103809460522417931793276236271880277656787655129047660393940467880928939929187487737450972412914141838476521934158496341, 151793875995232443957195041294619751417895712503979763273220578461973686330508709633351499372606258512592729863171960329052037608265950958785308716679174355684632290313326618991961149371913625095610744335903310600251034906825810585229087901861384965683431795935259583879892650423057694527874846310436985781993)
pri.decrypt(pub.encrypt(value=2, r_value=pri.p))
# -3122554952327851527065191331470214909195101670586965955975071315731426866149667779662210576472535592437515541888435595442001437808213154993423839723891841496776921477479597357853053308958677285920630751113117227964859312011304432998848291428529739442348873390760461234192227590787649292580169069156100013986550666965811019790548198613527215992055286250456750345576901096929278133149964456856040550974745150474788951005849050417525083553219445962265058144958360393978430179470948750038124710775075233211673977163929156615403705427283296117479305281423280385515699911899920326786653795234098751204300897964566302390194
```

I am not sure if this is the wrong implementation or deliberate behavior.  The paillier cipher works only if r value is relatively prime to n,  but the implementation here simply random r value from [1, n-1], which has a very low chance( it's (p + q - 1) / pq) leading to wrong decryption result.

**Comment by wilko77** [comment]
You are right that the Paillier cipher only works if _r_ is relative prime to _n_.
However, if you manage to find a _r_ that is not relative prime to _n_, then you have broken the security of the system, you can now officially factorize _n_ and thus decrypt.
The choice of the keylength accounts for that. For Example, with a 2048 bit _n_, the chances to find the factors _p_ or _q_ at random is somewhere in the order of 10 to the power of 300!!!!
We can probably agree that, in any practical sense, that means "never gonna happen".
